### ISSUE TITLE
The home directory doesn't exist, check your settings.

### ISSUE THREAD

**Issue by nallware** [realtimeprojects/quixplorer#28]
Firstly, thank you for providing open source products for those of us who are not as knowledgeable with PHP.  I'm still learning, this is why I chose QuiXplorer.  I read the readme.txt and it honestly looked
like it would be very simple to set up.  I first created a sub-directory on my hosting account with Godaddy called filemgr.  Then I loaded all your QuiXplorer project into that folder.  I followed the
directions to change the home_dir and home_url.  The unfortunate thing is I am getting an error that says "The home directory doesn't exist, check your settings. "

Can you offer any suggestions?

**Comment by realtimeprojects** [comment]
Hi, I am pretty sure that QuiXplorer is not able to read the home directory. I assume the directory is either not readable by the Webserver or you have a typo in your path. Make sure, the Webserver running Quixplorer is allowed to access that path.
